---
swagger: "2.0"
info:
  description: "Descubrir grupos de compras por coordenadas."
  version: "1.0.0"
  title: "GruposDiscovery"
host: "api.ingroupbuy.com"
basePath: "/v1"
schemes:
- "https"
paths:
  /groups/{coords}:
    get:
      summary: "Retorna los grupos de compras de acuerdo con las coordenadas recibidas."
      operationId: "groupsCoordsGET"
      produces:
      - "application/json"
      parameters:
      - name: "coords"
        in: "path"
        description: "Coordenadas a buscar."
        required: true
        type: "string"
      responses:
        "200":
          description: "Listado de grupos cercanos a la posición especificada"
          schema:
            $ref: "#/definitions/Group"
        "400":
          description: "Las coordenadas especificadas son inválidas."
        "404":
          description: "No se encontraron grupos de compras con las coordenadas especificadas."
        default:
          description: "Error inesperado"
      x-swagger-router-controller: "Default"
definitions:
  Group:
    required:
    - "coords"
    - "distance"
    - "id"
    - "name"
    properties:
      id:
        type: "integer"
      name:
        type: "string"
      coords:
        type: "string"
      distance:
        type: "integer"
    example:
      distance: 6
      name: "name"
      id: 0
      coords: "coords"
